"""Render outputs/evidence_report.md: the table leadership reads, regenerated every run."""
from __future__ import annotations

import pandas as pd

from .config import Config
from .model import window


def _md(df: pd.DataFrame) -> str:
    return df.to_markdown(index=False)


def write_evidence_report(cfg: Config, record: dict, tables: dict[str, pd.DataFrame]) -> str:
    s = tables["metrics_summary"]
    kpi = s.pivot_table(index=["metric_id", "metric", "unit"], columns="month",
                        values="value", aggfunc="first").reset_index()
    kpi.columns.name = None
    cols = ["metric_id", "metric", "unit"] + [m for m in cfg.months if m in kpi.columns] + ["ALL"]
    kpi = kpi[[c for c in cols if c in kpi.columns]].rename(columns={"ALL": "window"})

    start, end = window(cfg)
    targets = tables["rebalancing_targets"].head(15)[[
        "station_id", "station_name", "capacity", "dominant_pressure",
        "pct_days_needing_rebalance", "required_moves_per_day", "worst_weekday_hour",
        "observed_empty_pct", "observed_full_pct"]]
    v = tables["validation_report"]
    trips = record["inputs"]["trips"]
    raw_rows = sum(t["csv_rows"] for t in trips)
    snaps = record["inputs"]["gbfs_snapshots"]

    return f"""# Evidence report: Divvy station rebalancing

*Generated by `python -m divvy run`. Do not edit by hand.*

| | |
|---|---|
| Run id | `{record['run_id']}` |
| Status | **{record['status']}** |
| Trip months | {', '.join(cfg.months)} ({raw_rows:,} raw rides) |
| Operational days in KPI | {start} to {end} (04:00 to 04:00; final boundary day excluded) |
| GBFS snapshots | {len(snaps)} ({snaps[0]} to {snaps[-1]}) |

## KPI and metrics

{_md(kpi)}

**How to read M1–M4.** A station-day "needs rebalancing" when its intraday
swing (the peak bikes gained minus the deepest bikes lost since 04:00) is larger
than its dock capacity. On such a day no starting stock level could have kept
the station both rentable and returnable, so a truck or valet *must* have
intervened, or riders were turned away. M2 is therefore a **lower bound** on
the moves required.

## Where to send the trucks (top 15 of `rebalancing_targets.csv`)

`drain` stations run out of bikes, so they need bikes delivered.
`fill` stations run out of docks, so they need bikes removed.

{_md(targets)}

## Does the model match what riders see? (GBFS corroboration)

{_md(tables['corroboration_gbfs'])}

Status snapshots come from live polling during this project, not from the
trip months. Read this as directional evidence, not as a measured rate.

## Validation summary

{_md(v[['rule_id', 'severity', 'description', 'rows_affected', 'pct', 'passed', 'action']])}

## Known / Unknown / Assumption / Limitation

See `docs/05_known_unknowns.md` for the full list with reasoning.
"""
